# Generated by Django 2.2.28 on 2022-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
